### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by lekenny** [smallSohoSolo/android-developer-blog-cn#1]
可以不可以把要翻译的文章整理出一个列表出来,然后直接翻译

**Comment by owenlongbo** [comment]
可以的哈，还有几篇翻译好的没校验弄到主分支，明天我会弄好。我们翻译的列表是5.0以后的文章，也就是2016年所有的外带2015年后阶段的。这个区分会严格按照官方博客的排序。

**Comment by owenlongbo** [comment]
还有我的计划是用这个打开翻译这个渠道，然后弄个翻译屋web页面做翻译的站点，以后多多发翻译文章，感谢你的建议^_^

**Comment by lekenny** [comment]
@smallSohoSolo 为什么我fork到的仓库和你的不一样啊

**Comment by owenlongbo** [comment]
你fork的是主分支吗？
